### ISSUE TITLE
[WAIT] tambahin fitur downloader

### ISSUE THREAD

**Issue by cocoba88** [itsreimau/ckptw-wabot#11]
tambahin bang,, tambahkan fitur downloader doodstream 🥸

**Comment by itsreimau** [comment]
> tambahin bang,, tambahkan fitur downloader doodstream 🥸

otw!

**Comment by cocoba88** [comment]
mungkin referensi
https://www.npmjs.com/package/@onepunya/doods-warp?activeTab=versions
