### ISSUE TITLE
levelup

### ISSUE THREAD

**Issue by cocoba88** [itsreimau/ckptw-wabot#13]
/home/container/main.js:97
            xpToLevelUp = Math.floor(xpToLevelUp * 1.2);
                        ^
TypeError: Assignment to constant variable.
    at EventEmitter.<anonymous> (/home/container/main.js:97:25)
Node.js v20.17.0

dari const menjadi let
let xpToLevelUp = Math.floor(xpToLevelUp * 1.2);

// Pada bagian level up, di sekitar baris 100-an
let profilePictureUrl;
try {
    profilePictureUrl = await bot.core.profilePictureUrl(senderJid, "image"); // ganti jid dengan senderJid
} catch (error) {
    profilePictureUrl = global.config.bot.picture.profile;
}
const card = global.tools.api.createUrl("aggelos_007", "/levelup", {
    avatar: profilePictureUrl,
    level: newUserLevel
});

await ctx.reply({
    text: quote(`Selamat! Kamu telah naik ke level ${newUserLevel}!`),
    contextInfo: {
        mentionedJid: [senderJid], // ganti jid dengan senderJid
        externalAdReply: {
            mediaType: 1,
            previewType: 0,
            mediaUrl: global.config.bot.groupChat,
            title: "LEVEL UP",
            body: null,
            renderLargerThumbnail: true,
            thumbnailUrl: card || profilePictureUrl || global.config.bot.picture.thumbnail,
            sourceUrl: global.config.bot.groupChat
        }
    }
});

Saya mengganti jid dengan senderJid, yang sebelumnya sudah didefinisikan sebagai ctx.sender.jid.

**Comment by itsreimau** [comment]
udah di fix kok
