### ISSUE TITLE
[CLOSE - SOLVED] Set 'global.config.owner' Problems

### ISSUE THREAD

**Issue by SeYoox** [itsreimau/ckptw-wabot#14]
Config.js sudah saya set ownernya kok masih  belum bisa kenapa ya ?
![image](https://github.com/user-attachments/assets/5b3c353e-8462-45a6-a31f-ab6017449e0d)

**Comment by ahlaiptek** [comment]
Bisa tolong tampilkan scriptnya?

**Comment by itsreimau** [comment]
> Config.js sudah saya set ownernya kok masih belum bisa kenapa ya ? ![image](https://private-user-images.githubusercontent.com/183981058/373936434-5b3c353e-8462-45a6-a31f-ab6017449e0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODgzOTQsIm5iZiI6MTcyODI4ODA5NCwicGF0aCI6Ii8xODM5ODEwNTgvMzczOTM2NDM0LTViM2MzNTNlLTg0NjItNDVhNi1hMzFmLWFiNjAxNzQ0OWUwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwODAxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzZiYzI2ZGVlMzdiYmYwMTg0OGZlM2U1OWZlYTFjYWY2YWViN2VjZjUwYzUyMmViYTFlOTJmOGY3OWM2YzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ylqpEJ-ho-S_wVTpCFq8D6JajtZdQ4zGxKwyOjiv48o)

harus diubah namanya jadi config.js
