### ISSUE TITLE
Tambahkan fitur otomatis

### ISSUE THREAD

**Issue by dandyproject** [itsreimau/ckptw-wabot#16]
apa bisa dibuatkan event atau fitur otomatis seperti autodownloader ? yang mendeteksi link atau gambar tertentu?
terima kasih

**Comment by itsreimau** [comment]
> apa bisa dibuatkan event atau fitur otomatis seperti autodownloader ? yang mendeteksi link atau gambar tertentu? terima kasih

Memang agak sulit, jika membuat kodenya satu per satu akan memakan waktu lama, tapi mungkin bisa dilakukan dengan sistem callback. Saya sedang mengerjakan logikanya.
