### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by mdestafadilah** [itsreimau/ckptw-wabot#17]
Pak, support untuk REST API tidak?

**Comment by itsreimau** [comment]
> Pak, support untuk REST API tidak?

support, karena bot whatsapp ini 99% ambil sumber daya dari rest api

**Comment by mdestafadilah** [comment]
> > Pak, support untuk REST API tidak?
> 
> support, karena bot whatsapp ini 99% ambil sumber daya dari rest api

Contohnya kek mana pak?

**Comment by itsreimau** [comment]
> > > Pak, support untuk REST API tidak?
> > 
> > 
> > support, karena bot whatsapp ini 99% ambil sumber daya dari rest api
> 
> Contohnya kek mana pak?

cek aja di beberapa command yang memakai api

**Comment by mdestafadilah** [comment]
> > > > Pak, support untuk REST API tidak?
> > > 
> > > 
> > > support, karena bot whatsapp ini 99% ambil sumber daya dari rest api
> > 
> > 
> > Contohnya kek mana pak?
> 
> cek aja di beberapa command yang memakai api

bukan api dari luar pak, tp ckptw-wabot ini, apakah ada rest-api, agar saya bisa pakai endpoint dari ckpwt-wabot untuk kirim pesan/ file dari sistem saya juga pak

**Comment by itsreimau** [comment]
> > > > > Pak, support untuk REST API tidak?
> > > > 
> > > > 
> > > > support, karena bot whatsapp ini 99% ambil sumber daya dari rest api
> > > 
> > > 
> > > Contohnya kek mana pak?
> > 
> > 
> > cek aja di beberapa command yang memakai api
> 
> bukan api dari luar pak, tp ckptw-wabot ini, apakah ada rest-api, agar saya bisa pakai endpoint dari ckpwt-wabot untuk kirim pesan/ file dari sistem saya juga pak

oh seperti itu, gak ada pak. itu harus buat sendiri mungkin pake express

**Comment by mdestafadilah** [comment]
> > > > > > Pak, support untuk REST API tidak?
> > > > > 
> > > > > 
> > > > > support, karena bot whatsapp ini 99% ambil sumber daya dari rest api
> > > > 
> > > > 
> > > > Contohnya kek mana pak?
> > > 
> > > 
> > > cek aja di beberapa command yang memakai api
> > 
> > 
> > bukan api dari luar pak, tp ckptw-wabot ini, apakah ada rest-api, agar saya bisa pakai endpoint dari ckpwt-wabot untuk kirim pesan/ file dari sistem saya juga pak
> 
> oh seperti itu, gak ada pak. itu harus buat sendiri mungkin pake express

iya belum ada ya, sipp, nanti saya coba buat PR pak
