### ISSUE TITLE
connection closed due to  Error: Connection Failure

### ISSUE THREAD

**Issue by sitxxar** [itsreimau/ckptw-wabot#19]
![image](https://github.com/user-attachments/assets/a365cb8e-e242-4f75-8b8b-d4a199af5f69)

**Comment by itsreimau** [comment]
> ![image](https://private-user-images.githubusercontent.com/37711440/383965498-a365cb8e-e242-4f75-8b8b-d4a199af5f69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMTk5MDUsIm5iZiI6MTczMTAxOTYwNSwicGF0aCI6Ii8zNzcxMTQ0MC8zODM5NjU0OTgtYTM2NWNiOGUtZTI0Mi00Zjc1LThiOGItZDRhMTk5YWY1ZjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDIyNDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NDA5ZDBiMTc0YjMxZWQ3NTEwYWNhYmE2YjJmZGI5NzY2NDFkNDdmYjhmZmFkNWZiYzAxYjhhZWU5MDg4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RmmJ5ucEX9Mqcaw6RzJVneMSzX3EKO3krtvtxvGvvak)

maybe it's because of your network.

**Comment by sitxxar** [comment]
> > ![image](https://private-user-images.githubusercontent.com/37711440/383965498-a365cb8e-e242-4f75-8b8b-d4a199af5f69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMTk5MDUsIm5iZiI6MTczMTAxOTYwNSwicGF0aCI6Ii8zNzcxMTQ0MC8zODM5NjU0OTgtYTM2NWNiOGUtZTI0Mi00Zjc1LThiOGItZDRhMTk5YWY1ZjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDIyNDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NDA5ZDBiMTc0YjMxZWQ3NTEwYWNhYmE2YjJmZGI5NzY2NDFkNDdmYjhmZmFkNWZiYzAxYjhhZWU5MDg4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RmmJ5ucEX9Mqcaw6RzJVneMSzX3EKO3krtvtxvGvvak)
> 
> maybe it's because of your network.



no, previously I had successfully paired with the same network, but when I tried again an error occurred like that.

**Comment by itsreimau** [comment]
i don't know how to solve it

**Comment by itsreimau** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/37711440/383965498-a365cb8e-e242-4f75-8b8b-d4a199af5f69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMTk5MDUsIm5iZiI6MTczMTAxOTYwNSwicGF0aCI6Ii8zNzcxMTQ0MC8zODM5NjU0OTgtYTM2NWNiOGUtZTI0Mi00Zjc1LThiOGItZDRhMTk5YWY1ZjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDIyNDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NDA5ZDBiMTc0YjMxZWQ3NTEwYWNhYmE2YjJmZGI5NzY2NDFkNDdmYjhmZmFkNWZiYzAxYjhhZWU5MDg4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RmmJ5ucEX9Mqcaw6RzJVneMSzX3EKO3krtvtxvGvvak)
> > 
> > 
> > maybe it's because of your network.
> 
> no, previously I had successfully paired with the same network, but when I tried again an error occurred like that.

i don't know how to solve it

**Comment by iPanPS** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/37711440/383965498-a365cb8e-e242-4f75-8b8b-d4a199af5f69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMTk5MDUsIm5iZiI6MTczMTAxOTYwNSwicGF0aCI6Ii8zNzcxMTQ0MC8zODM5NjU0OTgtYTM2NWNiOGUtZTI0Mi00Zjc1LThiOGItZDRhMTk5YWY1ZjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDIyNDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NDA5ZDBiMTc0YjMxZWQ3NTEwYWNhYmE2YjJmZGI5NzY2NDFkNDdmYjhmZmFkNWZiYzAxYjhhZWU5MDg4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RmmJ5ucEX9Mqcaw6RzJVneMSzX3EKO3krtvtxvGvvak)
> > 
> > maybe it's because of your network.
> 
> 
> 
> no, previously I had successfully paired with the same network, but when I tried again an error occurred like that.

Try pair again
