### ISSUE TITLE
[CLOSE] How to fix this

### ISSUE THREAD

**Issue by Monster-Bunny** [itsreimau/ckptw-wabot#2]
# Heroku Node.js npm Install Buildpack
- Installing node modules
  - Using npm version `10.2.3`
  - Creating npm cache
  - Configuring npm cache directory
  - Running `npm ci "--production=false"`
      npm WARN config production Use `--omit=dev` instead.
      npm notice 
      npm notice New minor version of npm available! 10.2.3 -> 10.5.0
      npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.0>
      npm notice Run `npm install -g npm@10.5.0` to update!
      npm notice 
      npm ERR! code EUSAGE
      npm ERR! 
      npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
      npm ERR! 
      npm ERR! Invalid: lock file's sharp@0.30.7 does not satisfy sharp@0.32.6
      npm ERR! Invalid: lock file's node-addon-api@5.1.0 does not satisfy node-addon-api@6.1.0
      npm ERR! Missing: tar-fs@3.0.5 from lock file
      npm ERR! Missing: sharp@0.30.7 from lock file
      npm ERR! Missing: bare-fs@2.2.2 from lock file
      npm ERR! Missing: bare-path@2.1.0 from lock file
      npm ERR! Missing: tar-stream@3.1.7 from lock file
      npm ERR! Missing: bare-events@2.2.2 from lock file
      npm ERR! Missing: bare-os@2.2.1 from lock file
      npm ERR! Missing: streamx@2.16.1 from lock file
      npm ERR! Missing: fast-fifo@1.3.2 from lock file
      npm ERR! Missing: queue-tick@1.0.1 from lock file
      npm ERR! Missing: b4a@1.6.6 from lock file
      npm ERR! Missing: node-addon-api@5.1.0 from lock file
      npm ERR! Missing: semver@7.6.0 from lock file
      npm ERR! Missing: lru-cache@6.0.0 from lock file
      npm ERR! 
      npm ERR! Clean install a project
      npm ERR! 
      npm ERR! Usage:
      npm ERR! npm ci
      npm ERR! 
      npm ERR! Options:
      npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
      npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
      npm ERR! [--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
      npm ERR! [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
      npm ERR! [--no-bin-links] [--no-fund] [--dry-run]
      npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
      npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
      npm ERR! 
      npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
      npm ERR! 
      npm ERR! Run "npm help ci" for more info
      
      npm ERR! A complete log of this run can be found in: /layers/heroku_nodejs-npm-install/npm_cache/_logs/2024-03-30T22_02_45_303Z-debug-0.log
            
  - Done (0.940s)
- Debug info
  - Command failed `npm ci "--production=false"`
    exit status: 1
    stdout: <see above>
    stderr: <see above>
! Failed to install Node modules.
!
! The `Heroku Node.js npm Install Buildpack` uses the command `npm ci "--production=false"` to install your Node modules. This command failed and the buildpack cannot continue. See the log output above for more information.
!
! This error can occur due to an unstable network connection. Ensure that this command runs locally without error (exit status = 0) and retry your build.
!
! If that doesn’t help, check the status of the upstream Node module repository service at https://status.npmjs.org/.
ERROR: failed to build: exit status 1
exit status 51

**Comment by itsreimau** [comment]
Try using `npm i` or `npm i --force`.

**Comment by Monster-Bunny** [comment]
![git](https://github.com/itsreimau/ckptw-wabot/assets/141579057/fb749ea9-8368-4246-8cae-e53afe8c822c)

the same error keeps coming up 
I deploy it koybe 🥺🥺pis help me

**Comment by Monster-Bunny** [comment]
ytv, yta, play commands do not work

**Comment by itsreimau** [comment]
> ytv, yta, play commands do not work

I tried running it and it ran normally. By the way, this uses the **@bochilteam/scraper** module, maybe you don't have it installed. Try using `npm i @bochilteam/scraper`.

**Comment by Monster-Bunny** [comment]
reconnecting  true
Ready at 44258949466:4@s.whatsapp.net
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/workspace/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1711883616306,
    socket: 1711883616306,
    lookup: 1711883616313,
    connect: 1711883616316,
    secureConnect: 1711883616324,
    upload: 1711883616324,
    response: 1711883616332,
    end: 1711883616333,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 7,
      tcp: 3,
      tls: 8,
      request: 0,
      firstByte: 8,
      download: 1,
      total: 27
    }
  }
}
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/workspace/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1711883642936,
    socket: 1711883642936,
    lookup: 1711883642941,
    connect: 1711883642943,
    secureConnect: 1711883642949,
    upload: 1711883642949,
    response: 1711883642959,
    end: 1711883642960,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 5,
      tcp: 2,
      tls: 6,
      request: 0,
      firstByte: 10,
      download: 1,
      total: 24
  }
}

**Comment by cocoba88** [comment]
> reconnecting true Ready at 44258949466:[4@s.whatsapp.net](mailto:4@s.whatsapp.net) HTTPError: Response code 403 (Forbidden) at Request. (/workspace/node_modules/got/dist/source/as-promise/index.js:118:42) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { code: 'ERR_NON_2XX_3XX_RESPONSE', timings: { start: 1711883616306, socket: 1711883616306, lookup: 1711883616313, connect: 1711883616316, secureConnect: 1711883616324, upload: 1711883616324, response: 1711883616332, end: 1711883616333, error: undefined, abort: undefined, phases: { wait: 0, dns: 7, tcp: 3, tls: 8, request: 0, firstByte: 8, download: 1, total: 27 } } } HTTPError: Response code 403 (Forbidden) at Request. (/workspace/node_modules/got/dist/source/as-promise/index.js:118:42) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { code: 'ERR_NON_2XX_3XX_RESPONSE', timings: { start: 1711883642936, socket: 1711883642936, lookup: 1711883642941, connect: 1711883642943, secureConnect: 1711883642949, upload: 1711883642949, response: 1711883642959, end: 1711883642960, error: undefined, abort: undefined, phases: { wait: 0, dns: 5, tcp: 2, tls: 6, request: 0, firstByte: 10, download: 1, total: 24 } }

permasalahan yang sama

**Comment by Monster-Bunny** [comment]
@itsreimau

**Comment by itsreimau** [comment]
**HTTPError: Response code 403 (Forbidden)** occurs when the server has low specifications.
